### ISSUE TITLE
test hoe een issue werkt

### ISSUE THREAD

**Issue by maaikevc** [master-maker/master-maker#1]
Ik ben benieuwd wie deze issue ziet en hoe dat werkt, het plaatsen van een issue :)

**Comment by wooorm** [comment]
Iedereen die in [de organisatie zit](https://github.com/orgs/master-maker/people), en de mensen die dit project [watchen](https://github.com/master-maker/master-maker/watchers)!

**Comment by wooorm** [comment]
Als issues “afgerond” zijn, kan je ze sluiten, bij deze!
